### ISSUE TITLE
Unclear which options are part of Yoast SEO module

### ISSUE THREAD

**Issue by benvaassen** [Yoast/magento-seo#10]
In WordPress there is a menu item dedicated to our plugin called SEO with a clear logo, see screenshot: 
![general_-_yoast_seo_ _my_blog_ _wordpress](https://cloud.githubusercontent.com/assets/11910661/22462516/e0b9b848-e7ad-11e6-9929-6877c372459a.png)

In Magento it's unclear which settings are part of the Yoast SEO module (if there are any at all) see screenshot: 
![configuration___settings___stores___magento_admin](https://cloud.githubusercontent.com/assets/11910661/22462249/d3fc300a-e7ac-11e6-953b-e6dba1fc1e03.png)

**Comment by vincenthornikx** [comment]
A valid question. This module tries to re-use as much of Magento's own configuration as possible to avoid duplicate configuration fields for the same setting.
An argument can be made for moving all configuration to it's own section. I will discuss this with Yoast.

**Comment by vincenthornikx** [comment]
fixed in #15
