### ISSUE TITLE
Wrong Image ALT Attribute Analysis Report for Product Image

### ISSUE THREAD

**Issue by iamazik** [Yoast/magento-seo#11]
### What did you expect to happen?
The analysis should show the correct report while the product image doesn't contain the focus keyword in the ALT attribute.

### What happened instead?
It doesn't matter what ALT attribute you add on the product image, the analysis shows _The images on this page contain alt attributes with the focus keyword._, but it doesn't.

### How can we reproduce this behavior?

- Create a product
- Add some content and product image from the **Images and Videos** option
- Add focus keyword
- Add an image ALT attribute that doesn't contain the focus keyword
- See the content analysis report

### Screenshots
![screen shot 2017 01 31 at 8 18 11 pm](https://cloud.githubusercontent.com/assets/8946603/22468510/b459bfce-e7f2-11e6-8cfe-429400c49e30.png)
![screen shot 2017 01 31 at 8 18 54 pm](https://cloud.githubusercontent.com/assets/8946603/22468511/b462d97e-e7f2-11e6-9e15-69c4e0c42d78.png)

**Comment by vincenthornikx** [comment]
fixed in #16
