### ISSUE TITLE
Wrong Word Calculation Analysis Report

### ISSUE THREAD

**Issue by iamazik** [Yoast/magento-seo#12]
### What did you expect to happen?
The content analysis should calculate and show the number of words is being used accurately.

### What happened instead?
The analysis calculates the word from the content incorrectly. For your convenience, I've added the relevant content below. I've manually counted the words from the below content and there are 61 words. But, the analysis shows there are 64 words while using the following content on the products page. However, if you add the content on a page, the content analysis shows there are 63 words. Both of these are reports are incorrect.

On the other hand, if you use the following content in the WordPress, the Yoast SEO for WordPress count all the words correctly and shows the correct number, which is 61 words.

### Demo Content
Convenience is next to nothing when your day is crammed with action. So whether you're heading to class, gym, or the unbeaten path, make sure you've got your Strive Shoulder Pack stuffed with all your essentials, and extras as well.

- Zippered main compartment.
- Front zippered pocket.
- Side mesh pocket.
- Cell phone pocket on strap.
- Adjustable shoulder strap and top carry handle.

### How can we reproduce this behavior?
- Add the demo content to a product or a page
- See the analysis report about the word calculation

### Screenshots
![screen shot 2017 01 31 at 8 30 51 pm](https://cloud.githubusercontent.com/assets/8946603/22468889/4169980c-e7f4-11e6-9b5a-edb467f61f6e.png)
![screen shot 2017-01-31 at 8 30 46 pm](https://cloud.githubusercontent.com/assets/8946603/22468888/4165838e-e7f4-11e6-9153-6cfac58235ed.png)

**Comment by vincenthornikx** [comment]
The content which is analyzed is not exactly the same as the content of the Description field. In the SEO configuration you will see a template script. On the product edit page this template is rendered with live data from the form. The result is what is analyzed.

The default template contains the value of the name field and the value of the description field. In your example with 61 words in the description and 3 words in the product name this amounts to a total of 64 words.

The reason behind this mechanism is that a product page consists of possibly a lot more content than just the description field. Omitting or including content stored in other (even custom) product attributes could significantly change the analysis result. Using this mechanism enables you to include this content in the analysis.
