### ISSUE TITLE
"Search Engine Optimization by Yoast" should be "Yoast SEO"

### ISSUE THREAD

**Issue by omarreiss** [Yoast/magento-seo#18]
<img width="349" alt="screen shot 2017-04-04 at 21 39 44" src="https://cloud.githubusercontent.com/assets/1488816/24675463/8a35c8fa-197f-11e7-8e07-a62898c8841a.png">

Right now, I read "Search Engine Optimization by Yoast" everywhere. This should be "Yoast SEO" everywhere.

**Comment by vincenthornikx** [comment]
Done, will be fixed in 0.4.0
