### ISSUE TITLE
SEO score and Readability score missing / copy TYPO3 UX

### ISSUE THREAD

**Issue by omarreiss** [Yoast/magento-seo#19]
Right now, I think the interface in TYPO3 is much better.

Let's make it more or less the same in Magento. This means:

- One tab containing both analyzers titled "Analysis"
- An expandable box for the readability analysis with a readability score before the heading with copy "Readability". 
- An expandable box for the SEO analysis with an SEO score before the heading with copy "Focus keyword: **{focus_keyword_bold}**"
- The input field for the focus keyword inside the SEO analysis box.

<img width="876" alt="screen shot 2017-04-05 at 12 11 57" src="https://cloud.githubusercontent.com/assets/1488816/24701208/de9f4f04-19f9-11e7-99db-9ed12bdefaeb.png">

**Comment by vincenthornikx** [comment]
fixed in 0.4.0
