### ISSUE TITLE
Snippet preview design doesn't blend in nicely.

### ISSUE THREAD

**Issue by omarreiss** [Yoast/magento-seo#20]
Right now the snippet preview still has a design that is inspired by the way it was styled in Yoast SEO for WordPress a couple of versions back. The Yoast SEO settings look a bit like a mess of different design concepts:

<img width="1304" alt="screen shot 2017-04-05 at 12 29 21" src="https://cloud.githubusercontent.com/assets/1488816/24701662/9a9d6d20-19fb-11e7-9dbb-6c2586325f1c.png">

In TYPO3 we chose to blend it more with the page like this:

<img width="878" alt="screen shot 2017-04-05 at 12 27 48" src="https://cloud.githubusercontent.com/assets/1488816/24701632/6bdc4b82-19fb-11e7-93db-25d87283e9f1.png">

This is something I would also like to see for the Magento extension.
An alternative could also be to put the Snippet preview in an expandable box like the analyses in #19 

Please choose what is easiest to implement and takes the least time.

**Comment by vincenthornikx** [comment]
fixed in 0.4.0
