### ISSUE TITLE
Rel canonical missing.

### ISSUE THREAD

**Issue by omarreiss** [Yoast/magento-seo#21]
Currently, I don't see output for rel canonical on the frontend. Also I can't set it in the Yoast SEO settings. This is a pretty MVP feature that I expect to be in the extension. See https://github.com/Yoast/wordpress-seo/wiki/Yoast-SEO-product-sheet#technical-seo-out-of-the-box where it's listed in the Technical SEO out of the box section of the product sheet.

**Comment by vincenthornikx** [comment]
fixed in 0.4.0
