### ISSUE TITLE
Cannot remove images

### ISSUE THREAD

**Issue by omarreiss** [Yoast/magento-seo#23]
When I remove an image and I save, the image is still there:

Steps taken:

<img width="408" alt="joust_duffle_test___products___inventory___products___magento_admin" src="https://cloud.githubusercontent.com/assets/1488816/24704023/24dc6996-1a06-11e7-8717-08241356a5da.png">

<img width="357" alt="joust_duffle_test___products___inventory___products___magento_admin" src="https://cloud.githubusercontent.com/assets/1488816/24704040/3b2a4baa-1a06-11e7-9293-c1b7c5ee1399.png">

<img width="1331" alt="joust_duffle_test___products___inventory___products___magento_admin" src="https://cloud.githubusercontent.com/assets/1488816/24704077/602395d8-1a06-11e7-94cf-3001e5f53109.png">

<img width="630" alt="joust_duffle_test___products___inventory___products___magento_admin" src="https://cloud.githubusercontent.com/assets/1488816/24704121/8a511772-1a06-11e7-8743-9f87f31cc15c.png">

**Comment by omarreiss** [comment]
Same issue for Twitter image.

**Comment by vincenthornikx** [comment]
fixed in 0.4.0
