### ISSUE TITLE
Why is the meta keywords tab so prominently present? 

### ISSUE THREAD

**Issue by benvaassen** [Yoast/magento-seo#5]
Meta keywords shouldn't be used, they are well hidden and disabled by default in Yoast SEO for WordPress. In my opinion, they should be disabled by default in Magento as well: https://yoast.com/meta-keywords/

![home_page___pages___elements___content___magento_admin](https://cloud.githubusercontent.com/assets/11910661/22460740/93140e4c-e7a6-11e6-98ed-8812f1f378f8.png)

**Comment by omarreiss** [comment]
Meta keywords should just be disabled. If people still want to use it, we can choose to add a setting for that later to re-enable it.

**Comment by vincenthornikx** [comment]
fixed in 0.5.0
