### ISSUE TITLE
There is no SEO readability analysis

### ISSUE THREAD

**Issue by benvaassen** [Yoast/magento-seo#7]
Magento: 
![strive_shoulder_pack___products___inventory___products___magento_admin](https://cloud.githubusercontent.com/assets/11910661/22461158/6b3928c4-e7a8-11e6-9bcc-972d7bad27c2.png)
WordPress:
![add_new_post_ _local_wordpress_dev_devv_ _wordpress](https://cloud.githubusercontent.com/assets/11910661/22461175/79ad1a78-e7a8-11e6-9134-f2b846700cd2.png)

**Comment by vincenthornikx** [comment]
Has been fixed in #13
