### ISSUE TITLE
There is no overall SEO score

### ISSUE THREAD

**Issue by benvaassen** [Yoast/magento-seo#8]
Magento:![strive_shoulder_pack___products___inventory___products___magento_admin](https://cloud.githubusercontent.com/assets/11910661/22461216/ad2ea04c-e7a8-11e6-8abd-3b48e83620db.png)
In WordPress there are two ways to show the overall SEO and readability score, in the tab itself and in a separate block: 
![edit_post_ _local_wordpress_dev_devv_ _wordpress](https://cloud.githubusercontent.com/assets/11910661/22461481/bb01f286-e7a9-11e6-850a-767124b88b3c.png)
![edit_post_ _local_wordpress_dev_devv_ _wordpress](https://cloud.githubusercontent.com/assets/11910661/22461465/ac80a554-e7a9-11e6-90fb-a1d55c9e017d.png)

**Comment by omarreiss** [comment]
I respecified this issue in #19
