### ISSUE TITLE
When I disable MaxServ_YoastSEO it breaks the Search Engine Optimization by Yoast Module

### ISSUE THREAD

**Issue by benvaassen** [Yoast/magento-seo#9]
I go to Stores -> Configuration -> Advanced -> Advanced and I disable the last option, MaxServ_YoastSeo. When I then go and view a page I have broken two things. The first one that immediately stands out is the social fields: 
![strive_shoulder_pack___products___inventory___products___magento_admin](https://cloud.githubusercontent.com/assets/11910661/22461785/fa97fc0a-e7aa-11e6-91e1-bb3c1a3b0a71.png)

The second broken thing is the Search Engine Optimization by Yoast drop-down menu: 
![strive_shoulder_pack___products___inventory___products___magento_admin](https://cloud.githubusercontent.com/assets/11910661/22461821/249268ba-e7ab-11e6-8fc3-0fd1bcbb6d17.png)

**Comment by vincenthornikx** [comment]
fixed in #14
